import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDown, ArrowLeft, ArrowRight, Check, Cloud, Database, GitBranch, Layers3, Loader2, RefreshCw, ShieldCheck, Waypoints } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { getBuckets } from '../services/bucketService';
import { getAnalyticsKpis, getAnalyticsPrefixRecords } from '../services/analyticsService';
import { getActivityOverview, ActivityOverviewResponse } from '../services/dashboardService';
import { getOptimizationCandidates } from '../services/optimizationService';
import { getLifecyclePolicies } from '../services/lifecycleService';
import { getCostAnalysis } from '../services/costService';
import { getRegionalInfrastructure } from '../services/regionalService';
import { apiClient, getBackendStatus } from '../services/api';
import type { Bucket, OptimizationCandidate, LifecyclePolicy } from '../types';

type LensStatus = { connected?: boolean; dashboardCount?: number; configurations?: Array<{ Id?: string; IsEnabled?: boolean }>; activeDashboard?: { Id?: string; IsEnabled?: boolean; DataExport?: { CloudWatchMetrics?: { IsEnabled?: boolean } }; AccountLevel?: { ActivityMetrics?: { IsEnabled?: boolean }; AdvancedCostOptimizationMetrics?: { IsEnabled?: boolean }; PrefixLevel?: { StorageMetrics?: { IsEnabled?: boolean; SelectionCriteria?: { MinStorageBytesPercentage?: number; DelimiterDepth?: number } } } } }; error?: string; lastSynced?: string };
type WorkflowData = { buckets: Bucket[]; kpis: any; prefixes: any[]; candidates: OptimizationCandidate[]; policies: LifecyclePolicy[]; costs: any; regional: any; activity: ActivityOverviewResponse; lens: LensStatus };

const stages = [
  { name: 'STORE', short: 'Discover', icon: Database, explanation: 'Discover buckets and inspect their current region, size, object count, storage classes, encryption, versioning, and lifecycle configuration.' },
  { name: 'MONITOR', short: 'Observe', icon: Activity, explanation: 'Check Storage Lens configuration and separate configuration status from metric availability. Advanced metrics may take up to 48 hours to appear.' },
  { name: 'ANALYZE', short: 'Understand', icon: Layers3, explanation: 'Break down observed storage by bucket, region, class, and prefix. Request activity and history appear only when AWS supplies those observations.' },
  { name: 'OPTIMIZE', short: 'Recommend', icon: Waypoints, explanation: 'Review the existing optimization engine’s candidates, evidence, current and target classes, and volume-based estimated savings.' },
  { name: 'AUTOMATE', short: 'Govern', icon: GitBranch, explanation: 'Review actual lifecycle rules alongside recommendations. This workflow is read-only; any AWS write must be initiated and explicitly confirmed elsewhere.' },
  { name: 'EVALUATE', short: 'Measure', icon: ShieldCheck, explanation: 'Review estimated cost analysis and verified regional infrastructure. Before/after results require actual comparable observations.' },
];

const provenanceLabels: Record<string, string> = { LIVE_AWS: 'LIVE AWS', STORAGE_LENS: 'STORAGE LENS', CALCULATED_FROM_S3: 'CALCULATED', CALCULATED: 'CALCULATED', ESTIMATED: 'ESTIMATED', UNAVAILABLE: 'UNAVAILABLE', MOCK_FALLBACK: 'MOCK FALLBACK', 'mock-fallback': 'MOCK FALLBACK', 'aws-s3-hybrid': 'LIVE AWS' };
function Provenance({ value = 'UNAVAILABLE' }: { value?: string }) {
  const label = provenanceLabels[value] || value;
  const color = label === 'LIVE AWS' ? 'border-emerald-300 bg-emerald-50 text-emerald-800 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300' : label === 'STORAGE LENS' ? 'border-blue-300 bg-blue-50 text-blue-800 dark:border-blue-500/30 dark:bg-blue-500/10 dark:text-blue-300' : label === 'MOCK FALLBACK' || label === 'UNAVAILABLE' ? 'border-slate-300 bg-slate-100 text-slate-700 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-300' : 'border-amber-300 bg-amber-50 text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300';
  return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-bold tracking-wide ${color}`}>{label}</span>;
}

function Panel({ title, provenance, children }: { title: string; provenance?: string; children: React.ReactNode }) {
  return <section className="aws-card p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold text-slate-900 dark:text-slate-100">{title}</h3>{provenance && <Provenance value={provenance} />}</div>{children}</section>;
}

export const WorkflowPage: React.FC = () => {
  const [stage, setStage] = useState(0);
  const [data, setData] = useState<WorkflowData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [architecture, setArchitecture] = useState(false);
  const [revision, setRevision] = useState(0);
  useEffect(() => {
    let alive = true;
    Promise.allSettled([
      getBuckets(), getAnalyticsKpis(), getAnalyticsPrefixRecords(), getOptimizationCandidates(), getLifecyclePolicies(), getCostAnalysis(), getRegionalInfrastructure(), getActivityOverview(),
      apiClient<LensStatus>('/storage-lens/status', undefined, { connected: false, configurations: [], error: 'Backend unavailable' }),
    ]).then((results) => {
      if (!alive) return;
      const values: any[] = results.map((r) => r.status === 'fulfilled' ? r.value : null);
      setData({ buckets: values[0] || [], kpis: values[1], prefixes: values[2] || [], candidates: values[3] || [], policies: values[4] || [], costs: values[5], regional: values[6], activity: values[7] || { status: 'unavailable', provenance: 'UNAVAILABLE', observations: [], reason: 'Activity endpoint unavailable.' }, lens: values[8] || { connected: false, configurations: [] } });
      const failures = results.filter((r) => r.status === 'rejected').length;
      if (failures) setError(`${failures} data source${failures === 1 ? '' : 's'} could not be loaded. Unavailable panels do not use sample values.`);
      setLoading(false);
    });
    return () => { alive = false; };
  }, [revision]);
  const backendSource = getBackendStatus() === 'connected' ? 'LIVE_AWS' : 'UNAVAILABLE';
  const stageInfo = stages[stage];
  const storageTotal = useMemo(() => data?.buckets.reduce((sum, b) => sum + (b.storageGB * 1024 ** 3 || 0), 0) ?? 0, [data]);
  const totalFormatted = data?.kpis?.totalStorageFormatted || `${(storageTotal / 1024 ** 3).toFixed(2)} GB`;
  const lens = data?.lens;
  const actualLensConfig = lens?.activeDashboard;
  const isLensConfigured = !!actualLensConfig;
  const mainSource = backendSource;

  return <div className="space-y-6">
    <PageHeader title="Reviewer Workflow" subtitle="A read-only walkthrough of the S3 storage optimization lifecycle, backed by existing APIs and clearly labeled evidence." showDateRange={false} showRefresh={false} />
    <div className="aws-card p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-amber-600 dark:text-amber-400">Presentation mode · {stage + 1} of {stages.length}</div><h2 className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{stageInfo.name} <span className="text-slate-400">/</span> {stageInfo.short}</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-600 dark:text-slate-300">{stageInfo.explanation}</p></div><button className="btn-secondary" onClick={() => setArchitecture((v) => !v)}><GitBranch className="h-4 w-4" />{architecture ? 'Hide architecture' : 'Architecture view'}</button></div>
      <div className="mt-5 grid grid-cols-6 gap-1.5" aria-label={`Stage ${stage + 1} of ${stages.length}`}>{stages.map((item, i) => <button key={item.name} onClick={() => setStage(i)} aria-current={stage === i ? 'step' : undefined} className={`group h-2 rounded-full transition-colors ${i <= stage ? 'bg-amber-500' : 'bg-slate-200 dark:bg-slate-700'}`} title={item.name} />)}</div>
      <div className="mt-4 flex items-center justify-between"><button className="btn-secondary" disabled={stage === 0} onClick={() => setStage((n) => Math.max(0, n - 1))}><ArrowLeft className="h-4 w-4" />Previous</button><div className="flex items-center gap-2"><button className="btn-ghost" onClick={() => { setLoading(true); setError(''); setRevision((n) => n + 1); }} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh data</button><button className="btn-primary" disabled={stage === stages.length - 1} onClick={() => setStage((n) => Math.min(stages.length - 1, n + 1))}>Next<ArrowRight className="h-4 w-4" /></button></div></div>
    </div>

    {architecture && <Panel title="Technical architecture and data flow"><div className="grid gap-2 sm:grid-cols-7">{['Amazon S3', 'Storage Lens', 'Analysis engine', 'Optimization engine', 'Recommendations', 'Lifecycle automation', 'Storage efficiency'].map((label, i) => <React.Fragment key={label}><div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-center text-xs font-semibold text-slate-800 dark:border-white/10 dark:bg-slate-900/60 dark:text-slate-200">{label}<span className="mt-1 block text-[10px] font-normal text-slate-500">{['S3 APIs: buckets / objects / config', 'S3 Control configuration + exported metrics', 'analytics + regional APIs', 'optimization candidates API', 'reviewed in UI', 'lifecycle policies API', 'evaluated from observed data'][i]}</span></div>{i < 6 && <ArrowRight className="mx-auto hidden h-4 w-4 self-center text-amber-500 sm:block" />}</React.Fragment>)}</div><p className="mt-3 text-xs text-slate-500">Data flow: S3 → Storage Lens → analysis → recommendations → user-reviewed automation → measured efficiency. Workflow page performs read-only API requests.</p></Panel>}

    <div className="flex flex-wrap items-center gap-2 rounded-lg border border-slate-200 bg-white/70 p-3 dark:border-slate-700 dark:bg-slate-900/30"><span className="mr-1 text-xs font-semibold text-slate-600 dark:text-slate-300">Provenance</span>{['LIVE_AWS', 'STORAGE_LENS', 'CALCULATED', 'ESTIMATED', 'UNAVAILABLE'].map((v) => <Provenance key={v} value={v} />)}{loading && <span className="ml-auto flex items-center gap-1 text-xs text-slate-500"><Loader2 className="h-3 w-3 animate-spin"/>Loading API data…</span>}</div>
    {error && <div role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200">{error}</div>}
    {loading && !data ? <div className="aws-card flex items-center justify-center gap-2 p-12 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Fetching existing AWS-backed services…</div> : <>
      {stage === 0 && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Panel title="Discovered buckets" provenance={mainSource}><p className="text-2xl font-bold text-slate-900 dark:text-white">{data?.buckets.length ?? '—'}</p><p className="mt-1 text-xs text-slate-500">{totalFormatted} total observed storage <Provenance value="CALCULATED" /></p></Panel><Panel title="Object inventory" provenance="LIVE_AWS"><p className="text-2xl font-bold text-slate-900 dark:text-white">{data?.kpis?.totalObjectsFormatted ?? 'Unavailable'}</p><p className="mt-1 text-xs text-slate-500">Objects listed through the backend S3 API.</p></Panel><Panel title="Configuration coverage" provenance={mainSource}><p className="text-sm text-slate-700 dark:text-slate-300">Encryption, versioning, lifecycle rules, region and classes are returned per bucket where AWS allows discovery.</p></Panel></div><Panel title="Live bucket inventory" provenance={mainSource}><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead><tr>{['Bucket / region','Objects','Storage volume','Storage classes','Encryption','Versioning','Lifecycle'].map(x=><th key={x} className="border-b border-slate-200 px-3 py-2 font-semibold text-slate-500 dark:border-white/10">{x}</th>)}</tr></thead><tbody>{data?.buckets.map(b=><tr key={b.id || b.name} className="border-b border-slate-100 dark:border-white/5"><td className="px-3 py-3"><span className="font-semibold text-slate-800 dark:text-slate-200">{b.name}</span><span className="block text-slate-500">{b.region}</span></td><td className="px-3 py-3">{b.objectsFormatted}</td><td className="px-3 py-3">{b.storageGB.toFixed(3)} GB</td><td className="px-3 py-3">{b.storageByClass?.map(sc=>`${sc.class} (${sc.percentage}%)`).join(', ') || b.primaryStorageClass}</td><td className="px-3 py-3">{b.encryption || 'Unavailable'}</td><td className="px-3 py-3">{b.versioning ? 'Enabled' : 'Disabled'}</td><td className="px-3 py-3">{b.lifecycleRulesCount ?? 0} rules</td></tr>)}</tbody></table>{!data?.buckets.length && <p className="p-4 text-xs text-slate-500">No bucket inventory returned by the API.</p>}</div></Panel></div>}
      {stage === 1 && <div className="grid gap-4 md:grid-cols-2"><Panel title="Storage Lens configuration" provenance={isLensConfigured ? 'STORAGE_LENS' : 'UNAVAILABLE'}><p className="text-lg font-bold text-slate-900 dark:text-white">{actualLensConfig?.Id || 'No dashboard configuration returned'}</p><p className="mt-1 text-xs text-slate-500">{actualLensConfig?.IsEnabled ? 'Configuration enabled' : actualLensConfig ? 'Configuration disabled' : lens?.error || 'Status unavailable'}</p><p className="mt-3 text-xs text-slate-600 dark:text-slate-300">Dashboard configurations: {lens?.dashboardCount ?? data?.lens?.configurations?.length ?? 0}. Configuration metadata does not prove that metric datapoints have arrived.</p></Panel><Panel title="Activity data publication" provenance={data?.activity.provenance || 'UNAVAILABLE'}><p className="text-sm font-semibold text-slate-800 dark:text-slate-200">CloudWatch publishing: {actualLensConfig?.DataExport?.CloudWatchMetrics?.IsEnabled == null ? 'Status unavailable' : actualLensConfig.DataExport.CloudWatchMetrics.IsEnabled ? 'Enabled' : 'Disabled'}</p><p className="mt-2 text-xs leading-relaxed text-slate-600 dark:text-slate-300">Metric query: {data?.activity.status || 'unavailable'} · {data?.activity.observations.length || 0} daily observations. {data?.activity.reason || 'Verified Storage Lens values are available.'}</p><p className="mt-2 text-[11px] text-slate-500">AWS Storage Lens activity metrics publish daily; first CloudWatch publication can take up to 24 hours. No sample values are substituted.</p></Panel><Panel title="What Storage Lens does"><p className="text-xs leading-relaxed text-slate-600 dark:text-slate-300">Storage Lens aggregates organization or account level usage and activity metrics, supports prefix aggregation, and can publish selected metrics to CloudWatch / export them. Current S3 inventory remains sourced from direct S3 APIs until real Storage Lens metric exports are available.</p></Panel><Panel title="Configuration controls reported"><ul className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><li>Activity metrics: {actualLensConfig?.AccountLevel?.ActivityMetrics?.IsEnabled == null ? 'Status unavailable' : actualLensConfig.AccountLevel.ActivityMetrics.IsEnabled ? 'Enabled' : 'Disabled'}</li><li>Advanced cost optimization: {actualLensConfig?.AccountLevel?.AdvancedCostOptimizationMetrics?.IsEnabled == null ? 'Status unavailable' : actualLensConfig.AccountLevel.AdvancedCostOptimizationMetrics.IsEnabled ? 'Enabled' : 'Disabled'}</li><li>Prefix aggregation: {actualLensConfig?.AccountLevel?.PrefixLevel?.StorageMetrics?.IsEnabled == null ? 'Status unavailable' : actualLensConfig.AccountLevel.PrefixLevel.StorageMetrics.IsEnabled ? 'Enabled' : 'Disabled'}</li><li>Last configuration read: {lens?.lastSynced ? new Date(lens.lastSynced).toLocaleString() : 'Unavailable'}</li></ul></Panel></div>}
      {stage === 2 && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Panel title="Observed storage" provenance="CALCULATED"><strong className="text-xl text-slate-900 dark:text-white">{totalFormatted}</strong><p className="mt-1 text-xs text-slate-500">Summed from current S3 object listings.</p></Panel><Panel title="Observed prefix records" provenance={mainSource}><strong className="text-xl text-slate-900 dark:text-white">{data?.prefixes.length ?? 0}</strong></Panel><Panel title="Business activity metrics" provenance={data?.activity.provenance || 'UNAVAILABLE'}><strong className="text-sm text-slate-700 dark:text-slate-300">{data?.activity.status === 'available' ? `${data.activity.observations.length} daily observations` : data?.activity.status === 'pending' ? 'Pending from CloudWatch' : 'Unavailable'}</strong><p className="mt-1 text-xs text-slate-600 dark:text-slate-400">{data?.activity.reason || 'Published Storage Lens activity metrics.'}</p></Panel></div><Panel title="Bucket and region breakdown" provenance={mainSource}><div className="grid gap-2 md:grid-cols-2">{data?.buckets.map(b=><div key={b.name} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2 text-xs dark:bg-slate-900/60"><span>{b.name} <span className="text-slate-500">· {b.region}</span></span><span>{b.storageGB.toFixed(3)} GB · {b.objectsFormatted} objects</span></div>)}</div></Panel><Panel title="Storage class distribution" provenance="CALCULATED"><div className="grid gap-2 sm:grid-cols-2">{data?.buckets.flatMap(b=>b.storageByClass?.map(sc=><div key={`${b.name}-${sc.class}`} className="flex justify-between rounded-lg border border-slate-200 px-3 py-2 text-xs dark:border-white/10"><span>{sc.class} <span className="text-slate-500">· {b.name}</span></span><span>{sc.gb.toFixed(3)} GB ({sc.percentage}%)</span></div>) || [])}</div></Panel><Panel title="Prefix observations" provenance={mainSource}><div className="max-h-72 overflow-auto">{data?.prefixes.slice(0,100).map((p:any)=><div key={p.id} className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-slate-100 py-2 text-xs dark:border-white/5"><span className="truncate">{p.bucket}/{p.prefix}</span><span>{p.storageFormatted}</span><span>{p.objectsFormatted} objects</span></div>)}{!data?.prefixes.length&&<p className="text-xs text-slate-500">No prefix records were returned. Prefix analysis requires the backend’s actual inventory or Storage Lens prefix export.</p>}</div></Panel></div>}
      {stage === 3 && <Panel title="Optimization candidates" provenance={mainSource}><p className="mb-4 text-xs text-slate-500">Candidates are generated by the existing optimization service. Volume savings are estimates; LastModified is not treated as LastAccessed.</p><div className="space-y-3">{data?.candidates.map(c=><article key={c.id} className="rounded-xl border border-slate-200 p-4 dark:border-white/10"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="text-sm font-bold text-slate-900 dark:text-slate-100">{c.bucket} · {c.prefix}</h4><p className="mt-1 text-xs text-slate-500">{c.objectCountFormatted} objects · {c.storageFormatted}</p></div><span className="flex gap-1"><Provenance value="LIVE_AWS"/><Provenance value="ESTIMATED"/></span></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-3"><div>Current class <strong>{c.currentStorageClass}</strong></div><div>Recommended class <strong>{c.targetStorageClass}</strong></div><div>Estimated savings <strong>{c.savingsFormatted || `$${c.estimatedMonthlyDifference.toFixed(2)}/mo`}</strong></div></div><p className="mt-2 text-xs text-slate-600 dark:text-slate-300">{c.reason}</p><p className="mt-1 text-xs text-slate-500">Evidence: {c.evidenceUsed || c.analysisText}</p><p className="mt-1 text-[11px] text-slate-500">Activity evidence: {c.accessMetricsStatus || 'UNAVAILABLE'} · Access requests: {c.getRequests == null ? 'UNAVAILABLE' : c.getRequests}</p></article>)}{!data?.candidates.length&&<p className="text-xs text-slate-500">No candidates returned by the optimization service.</p>}</div></Panel>}
      {stage === 4 && <div className="space-y-4"><Panel title="Existing lifecycle rules" provenance={mainSource}><p className="mb-3 text-xs text-slate-500">Rules below reflect backend lifecycle-policy results. Recommendations do not alter bucket configuration. No AWS write is performed by this reviewer workflow.</p><div className="space-y-2">{data?.policies.map(p=><div key={p.id} className="grid gap-1 rounded-lg border border-slate-200 p-3 text-xs dark:border-white/10 sm:grid-cols-4"><span className="font-semibold">{p.bucket}</span><span>{p.policyName} · {p.status}</span><span>{p.prefix} · {p.transitionDays ?? '—'} day transition</span><span>{p.targetClass} · {p.expirationDays ?? '—'} day expiration</span></div>)}{!data?.policies.length&&<p className="text-xs text-slate-500">No lifecycle policies returned from AWS-backed API.</p>}</div></Panel><Panel title="Recommended governance"><p className="text-xs leading-relaxed text-slate-600 dark:text-slate-300">Review optimization candidates for policy suggestions. Recommendations become AWS configuration only after an explicit user action and confirmation. Lifecycle configuration write behavior is not triggered from this page.</p></Panel></div>}
      {stage === 5 && <div className="grid gap-4 md:grid-cols-2"><Panel title="Cost analysis" provenance="ESTIMATED"><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-600 dark:text-slate-300">{data?.costs ? JSON.stringify(data.costs, null, 2) : 'Cost data unavailable.'}</pre><p className="mt-3 text-xs text-slate-500">Actual AWS billing is not connected through this workflow. Treat cost figures as estimates unless explicitly marked actual by source API.</p></Panel><Panel title="Regional infrastructure" provenance={data?.regional?.dataSource || 'UNAVAILABLE'}><div className="space-y-2 text-xs">{data?.regional?.regions?.map((r:any)=><div key={r.region || r.name} className="flex justify-between rounded-lg bg-slate-50 p-2 dark:bg-slate-900/60"><span>{r.region || r.name}</span><span>{r.bucketCount ?? '—'} buckets</span></div>) || <p className="text-slate-500">Regional data unavailable.</p>}</div><p className="mt-3 text-xs text-slate-500">Replication status and latency are shown only when explicitly verified by source data; no values are inferred here.</p></Panel><Panel title="Before / after evaluation" provenance="UNAVAILABLE"><p className="text-xs leading-relaxed text-slate-600 dark:text-slate-300">No verified before/after baseline is available yet. Current inventory is a point-in-time observation, and Storage Lens history is pending. Compare only when real, timestamped observations exist.</p></Panel><Panel title="Evidence summary"><div className="space-y-2 text-xs text-slate-600 dark:text-slate-300"><p><Check className="mr-1 inline h-3.5 w-3.5 text-emerald-500"/>S3 inventory and bucket configuration come from existing AWS-backed endpoints.</p><p><Cloud className="mr-1 inline h-3.5 w-3.5 text-blue-500"/>Storage Lens metrics are separate and may be pending.</p><p><ArrowDown className="mr-1 inline h-3.5 w-3.5 text-amber-500"/>Storage volume and savings are calculated estimates.</p></div></Panel></div>}
    </>}
  </div>;
};
